### PR TITLE
User questionnaires

### PR DESCRIPTION
**Pull request by bannastre**

### CODE REVIEW

**Comment by rogrenke** [comment]
Hey! Good first shot. I just added some additional questions - what do you think about them?

* In general:
    * When you are learning yourself, what keeps you engaged?
    * What motivates you to complete a list of tasks?
    * In your opinion, what are the best channels for mentors / mentees to communicate? [does Google form has a functionality to rank answers? not sure]

* As a mentee:
    * Have you been a mentee before? (y/n)
    * What do you consider best practices as a mentee? How do you get most out of a session with a mentor?
    * What was the most impactful advice you have been given by a mentor?
    * In the past, have you wished that a mentor provide you with additional materials (e.g. articles, podcasts, videos - not just vocal advice)? 
    * Did a mentor assigned you tasks in the past? (y/n)
        * If yes, was that helpful? (y/n)
        * If yes, what was the incentive to complete the tasks?

* As a mentor:
    * Have you been a mentor before? (y/n)
    * What do you consider main responsibilities as a mentor?
    * What was the most impactful advice you have given a mentee?
    * In the past, have you wished to have an easy way to provide additional content to a mentee (e.g. articles, podcasts, videos)?
    * Have you thought about rewarding your mentee for certain behavior?
        * if yes, what type of reward would be appropriate?

**Comment by sampritchard** [comment]
Hey Roland - some nice additional questions in there. I would be weary of having too many Q's though for a google form and for the cohort. Unlikely that they would remain engaged if over 5/6 questions but open to hearing what others thing?

**Comment by rogrenke** [comment]
Agreed! In general, I assume that most of the yes/no questions are not really harmful in this regard. Nevertheless, agreed that those are too many - it was more thought as a brain-dump. Feel free to take them as additional inspiration. Especially the ones about multi-media are not relevant to the current features that we are building.

Also, is there a possibility to hide some questions in google forms and that those questions only appear for a specific answer? (e.g. if a person says that she has never been a mentor, there is no need for all the specific mentor questions)

**Comment by marioribeiro** [comment]
:shipit:

**Review by marioribeiro — APPROVED** [review]

**Pull request merged**
